//! Consensus-compatible decoder for `ProtoArgs`.
//!
//! Contract arguments are consensus input: a contract can pass arbitrary bytes
//! as the arguments of a cross-contract call, and every node must accept or
//! reject them identically. The upstream network decodes them with code
//! generated by rust-protobuf 2.27.1. rust-protobuf 3 is more lenient (for
//! example, it silently skips a known field sent with the wrong wire type), so
//! using its generated parser here would let this node execute calls that the
//! rest of the network rejects.
//!
//! This decoder reproduces the acceptance rules and results of the
//! rust-protobuf 2.27.1 generated `ProtoArgs::parse_from_bytes`:
//!
//! - varints are at most 10 bytes; bits beyond 64 are dropped;
//! - tags, `bool` values and `bytes` lengths are varints truncated to 32 bits;
//! - nested message lengths are full 64-bit varints. They only set a logical
//!   limit: the top-level limit is unbounded, so an argument that declares
//!   more bytes than remain is parsed up to the end of the input;
//! - a known field with an unexpected wire type is an error;
//! - unknown fields are skipped; a start-group is skipped up to the next
//!   end-group of any field number, and a group nested in a group is an error;
//! - a stray end-group, wire types 6 and 7, and field number 0 are errors.
//!
//! `fuzz/proto-args-differential` checks this decoder against the original
//! rust-protobuf 2.27.1 generated code. Do not change it without running that
//! test.

use std::fmt;

use super::models::proto_args::Argument;

const WIRE_VARINT: u32 = 0;
const WIRE_FIXED64: u32 = 1;
const WIRE_LENGTH_DELIMITED: u32 = 2;
const WIRE_START_GROUP: u32 = 3;
const WIRE_END_GROUP: u32 = 4;
const WIRE_FIXED32: u32 = 5;

const MAX_VARINT_LEN: usize = 10;
const NO_LIMIT: u64 = u64::MAX;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecodeError {
    UnexpectedEof,
    IncorrectVarint,
    IncorrectTag(u32),
    UnexpectedWireType(u32),
    LimitOverflow,
    TruncatedMessage,
}

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DecodeError::UnexpectedEof => write!(f, "unexpected EOF"),
            DecodeError::IncorrectVarint => write!(f, "incorrect varint"),
            DecodeError::IncorrectTag(tag) => write!(f, "incorrect tag: {}", tag),
            DecodeError::UnexpectedWireType(wire_type) => {
                write!(f, "unexpected wire type: {}", wire_type)
            }
            DecodeError::LimitOverflow => write!(f, "message length exceeds limit"),
            DecodeError::TruncatedMessage => write!(f, "truncated message"),
        }
    }
}

impl std::error::Error for DecodeError {}

type DecodeResult<T> = Result<T, DecodeError>;

/// Decodes the protobuf payload of contract arguments (without the leading
/// format byte).
pub fn decode_proto_args(data: &[u8]) -> DecodeResult<Vec<Argument>> {
    let mut reader = Reader {
        data,
        pos: 0,
        limit: NO_LIMIT,
    };
    let mut args = Vec::new();

    while !reader.eof() {
        let (field_number, wire_type) = reader.read_tag()?;
        match field_number {
            1 => {
                if wire_type != WIRE_LENGTH_DELIMITED {
                    return Err(DecodeError::UnexpectedWireType(wire_type));
                }
                args.push(reader.read_argument()?);
            }
            _ => reader.read_unknown_or_skip_group(wire_type)?,
        }
    }

    Ok(args)
}

struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
    /// Logical limit set by enclosing messages, as in rust-protobuf 2. It can
    /// be past the end of `data`.
    limit: u64,
}

impl<'a> Reader<'a> {
    /// End of readable input: the logical limit or the end of the data.
    fn end(&self) -> usize {
        self.limit.min(self.data.len() as u64) as usize
    }

    fn eof(&self) -> bool {
        self.pos == self.end()
    }

    fn read_byte(&mut self) -> DecodeResult<u8> {
        if self.eof() {
            return Err(DecodeError::UnexpectedEof);
        }
        let byte = self.data[self.pos];
        self.pos += 1;
        Ok(byte)
    }

    fn read_varint64(&mut self) -> DecodeResult<u64> {
        let mut value: u64 = 0;
        for i in 0..MAX_VARINT_LEN {
            let byte = self.read_byte()?;
            // The tenth byte contributes only its lowest bit; higher bits are
            // dropped, as in rust-protobuf 2.
            value |= u64::from(byte & 0x7f) << (i * 7);
            if byte < 0x80 {
                return Ok(value);
            }
        }
        Err(DecodeError::IncorrectVarint)
    }

    fn read_varint32(&mut self) -> DecodeResult<u32> {
        self.read_varint64().map(|value| value as u32)
    }

    fn read_tag(&mut self) -> DecodeResult<(u32, u32)> {
        let tag = self.read_varint32()?;
        let wire_type = tag & 0x7;
        let field_number = tag >> 3;
        if wire_type > WIRE_FIXED32 || field_number == 0 {
            return Err(DecodeError::IncorrectTag(tag));
        }
        Ok((field_number, wire_type))
    }

    fn read_raw_bytes(&mut self, len: u32) -> DecodeResult<&'a [u8]> {
        let len = len as usize;
        if len > self.end() - self.pos {
            return Err(DecodeError::TruncatedMessage);
        }
        let bytes = &self.data[self.pos..self.pos + len];
        self.pos += len;
        Ok(bytes)
    }

    fn read_argument(&mut self) -> DecodeResult<Argument> {
        let len = self.read_varint64()?;
        let new_limit = (self.pos as u64)
            .checked_add(len)
            .ok_or(DecodeError::LimitOverflow)?;
        if new_limit > self.limit {
            return Err(DecodeError::LimitOverflow);
        }
        let old_limit = std::mem::replace(&mut self.limit, new_limit);

        let mut arg = Argument::new();
        while !self.eof() {
            let (field_number, wire_type) = self.read_tag()?;
            match field_number {
                1 => {
                    if wire_type != WIRE_LENGTH_DELIMITED {
                        return Err(DecodeError::UnexpectedWireType(wire_type));
                    }
                    let len = self.read_varint32()?;
                    arg.value = self.read_raw_bytes(len)?.to_vec();
                }
                2 => {
                    if wire_type != WIRE_VARINT {
                        return Err(DecodeError::UnexpectedWireType(wire_type));
                    }
                    arg.is_nil = self.read_varint32()? != 0;
                }
                _ => self.read_unknown_or_skip_group(wire_type)?,
            }
        }

        self.limit = old_limit;
        Ok(arg)
    }

    fn read_unknown_or_skip_group(&mut self, wire_type: u32) -> DecodeResult<()> {
        if wire_type == WIRE_START_GROUP {
            self.skip_group()
        } else {
            self.read_unknown(wire_type)
        }
    }

    fn skip_group(&mut self) -> DecodeResult<()> {
        loop {
            let (_, wire_type) = self.read_tag()?;
            if wire_type == WIRE_END_GROUP {
                return Ok(());
            }
            self.read_unknown(wire_type)?;
        }
    }

    fn read_unknown(&mut self, wire_type: u32) -> DecodeResult<()> {
        match wire_type {
            WIRE_VARINT => self.read_varint64().map(|_| ()),
            WIRE_FIXED64 => self.read_raw_bytes(8).map(|_| ()),
            WIRE_FIXED32 => self.read_raw_bytes(4).map(|_| ()),
            WIRE_LENGTH_DELIMITED => {
                let len = self.read_varint32()?;
                self.read_raw_bytes(len).map(|_| ())
            }
            _ => Err(DecodeError::UnexpectedWireType(wire_type)),
        }
    }
}
