// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `models.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:models.ProtoArgs)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProtoArgs {
    // message fields
    // @@protoc_insertion_point(field:models.ProtoArgs.args)
    pub args: ::std::vec::Vec<proto_args::Argument>,
    // special fields
    // @@protoc_insertion_point(special_field:models.ProtoArgs.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProtoArgs {
    fn default() -> &'a ProtoArgs {
        <ProtoArgs as ::protobuf::Message>::default_instance()
    }
}

impl ProtoArgs {
    pub fn new() -> ProtoArgs {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "args",
            |m: &ProtoArgs| { &m.args },
            |m: &mut ProtoArgs| { &mut m.args },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProtoArgs>(
            "ProtoArgs",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProtoArgs {
    const NAME: &'static str = "ProtoArgs";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.args.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.args {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.args {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProtoArgs {
        ProtoArgs::new()
    }

    fn clear(&mut self) {
        self.args.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProtoArgs {
        static instance: ProtoArgs = ProtoArgs {
            args: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProtoArgs {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProtoArgs").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProtoArgs {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoArgs {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ProtoArgs`
pub mod proto_args {
    // @@protoc_insertion_point(message:models.ProtoArgs.Argument)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Argument {
        // message fields
        // @@protoc_insertion_point(field:models.ProtoArgs.Argument.value)
        pub value: ::std::vec::Vec<u8>,
        // @@protoc_insertion_point(field:models.ProtoArgs.Argument.is_nil)
        pub is_nil: bool,
        // special fields
        // @@protoc_insertion_point(special_field:models.ProtoArgs.Argument.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Argument {
        fn default() -> &'a Argument {
            <Argument as ::protobuf::Message>::default_instance()
        }
    }

    impl Argument {
        pub fn new() -> Argument {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "value",
                |m: &Argument| { &m.value },
                |m: &mut Argument| { &mut m.value },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "is_nil",
                |m: &Argument| { &m.is_nil },
                |m: &mut Argument| { &mut m.is_nil },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Argument>(
                "ProtoArgs.Argument",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Argument {
        const NAME: &'static str = "Argument";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.value = is.read_bytes()?;
                    },
                    16 => {
                        self.is_nil = is.read_bool()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.value.is_empty() {
                my_size += ::protobuf::rt::bytes_size(1, &self.value);
            }
            if self.is_nil != false {
                my_size += 1 + 1;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.value.is_empty() {
                os.write_bytes(1, &self.value)?;
            }
            if self.is_nil != false {
                os.write_bool(2, self.is_nil)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Argument {
            Argument::new()
        }

        fn clear(&mut self) {
            self.value.clear();
            self.is_nil = false;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Argument {
            static instance: Argument = Argument {
                value: ::std::vec::Vec::new(),
                is_nil: false,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Argument {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("ProtoArgs.Argument").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Argument {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Argument {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

// @@protoc_insertion_point(message:models.Action)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Action {
    // message fields
    // @@protoc_insertion_point(field:models.Action.action_type)
    pub action_type: u32,
    // @@protoc_insertion_point(field:models.Action.amount)
    pub amount: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.Action.method)
    pub method: ::std::string::String,
    // @@protoc_insertion_point(field:models.Action.args)
    pub args: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.Action.gas_limit)
    pub gas_limit: u64,
    // @@protoc_insertion_point(field:models.Action.code)
    pub code: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.Action.nonce)
    pub nonce: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.Action.key)
    pub key: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:models.Action.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Action {
    fn default() -> &'a Action {
        <Action as ::protobuf::Message>::default_instance()
    }
}

impl Action {
    pub fn new() -> Action {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "action_type",
            |m: &Action| { &m.action_type },
            |m: &mut Action| { &mut m.action_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "amount",
            |m: &Action| { &m.amount },
            |m: &mut Action| { &mut m.amount },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "method",
            |m: &Action| { &m.method },
            |m: &mut Action| { &mut m.method },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "args",
            |m: &Action| { &m.args },
            |m: &mut Action| { &mut m.args },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "gas_limit",
            |m: &Action| { &m.gas_limit },
            |m: &mut Action| { &mut m.gas_limit },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "code",
            |m: &Action| { &m.code },
            |m: &mut Action| { &mut m.code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "nonce",
            |m: &Action| { &m.nonce },
            |m: &mut Action| { &mut m.nonce },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &Action| { &m.key },
            |m: &mut Action| { &mut m.key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Action>(
            "Action",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Action {
    const NAME: &'static str = "Action";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.action_type = is.read_uint32()?;
                },
                18 => {
                    self.amount = is.read_bytes()?;
                },
                26 => {
                    self.method = is.read_string()?;
                },
                34 => {
                    self.args = is.read_bytes()?;
                },
                40 => {
                    self.gas_limit = is.read_uint64()?;
                },
                50 => {
                    self.code = is.read_bytes()?;
                },
                58 => {
                    self.nonce = is.read_bytes()?;
                },
                66 => {
                    self.key = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.action_type != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.action_type);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.amount);
        }
        if !self.method.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.method);
        }
        if !self.args.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.args);
        }
        if self.gas_limit != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.gas_limit);
        }
        if !self.code.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.code);
        }
        if !self.nonce.is_empty() {
            my_size += ::protobuf::rt::bytes_size(7, &self.nonce);
        }
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(8, &self.key);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.action_type != 0 {
            os.write_uint32(1, self.action_type)?;
        }
        if !self.amount.is_empty() {
            os.write_bytes(2, &self.amount)?;
        }
        if !self.method.is_empty() {
            os.write_string(3, &self.method)?;
        }
        if !self.args.is_empty() {
            os.write_bytes(4, &self.args)?;
        }
        if self.gas_limit != 0 {
            os.write_uint64(5, self.gas_limit)?;
        }
        if !self.code.is_empty() {
            os.write_bytes(6, &self.code)?;
        }
        if !self.nonce.is_empty() {
            os.write_bytes(7, &self.nonce)?;
        }
        if !self.key.is_empty() {
            os.write_bytes(8, &self.key)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Action {
        Action::new()
    }

    fn clear(&mut self) {
        self.action_type = 0;
        self.amount.clear();
        self.method.clear();
        self.args.clear();
        self.gas_limit = 0;
        self.code.clear();
        self.nonce.clear();
        self.key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Action {
        static instance: Action = Action {
            action_type: 0,
            amount: ::std::vec::Vec::new(),
            method: ::std::string::String::new(),
            args: ::std::vec::Vec::new(),
            gas_limit: 0,
            code: ::std::vec::Vec::new(),
            nonce: ::std::vec::Vec::new(),
            key: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Action {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Action").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Action {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Action {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:models.ActionResult)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ActionResult {
    // message fields
    // @@protoc_insertion_point(field:models.ActionResult.input_action)
    pub input_action: ::protobuf::MessageField<Action>,
    // @@protoc_insertion_point(field:models.ActionResult.success)
    pub success: bool,
    // @@protoc_insertion_point(field:models.ActionResult.error)
    pub error: ::std::string::String,
    // @@protoc_insertion_point(field:models.ActionResult.gas_used)
    pub gas_used: u64,
    // @@protoc_insertion_point(field:models.ActionResult.remaining_gas)
    pub remaining_gas: u64,
    // @@protoc_insertion_point(field:models.ActionResult.output_data)
    pub output_data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:models.ActionResult.sub_action_results)
    pub sub_action_results: ::std::vec::Vec<ActionResult>,
    // @@protoc_insertion_point(field:models.ActionResult.contract)
    pub contract: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:models.ActionResult.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ActionResult {
    fn default() -> &'a ActionResult {
        <ActionResult as ::protobuf::Message>::default_instance()
    }
}

impl ActionResult {
    pub fn new() -> ActionResult {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Action>(
            "input_action",
            |m: &ActionResult| { &m.input_action },
            |m: &mut ActionResult| { &mut m.input_action },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "success",
            |m: &ActionResult| { &m.success },
            |m: &mut ActionResult| { &mut m.success },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error",
            |m: &ActionResult| { &m.error },
            |m: &mut ActionResult| { &mut m.error },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "gas_used",
            |m: &ActionResult| { &m.gas_used },
            |m: &mut ActionResult| { &mut m.gas_used },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "remaining_gas",
            |m: &ActionResult| { &m.remaining_gas },
            |m: &mut ActionResult| { &mut m.remaining_gas },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "output_data",
            |m: &ActionResult| { &m.output_data },
            |m: &mut ActionResult| { &mut m.output_data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "sub_action_results",
            |m: &ActionResult| { &m.sub_action_results },
            |m: &mut ActionResult| { &mut m.sub_action_results },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "contract",
            |m: &ActionResult| { &m.contract },
            |m: &mut ActionResult| { &mut m.contract },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ActionResult>(
            "ActionResult",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ActionResult {
    const NAME: &'static str = "ActionResult";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.input_action)?;
                },
                16 => {
                    self.success = is.read_bool()?;
                },
                26 => {
                    self.error = is.read_string()?;
                },
                32 => {
                    self.gas_used = is.read_uint64()?;
                },
                40 => {
                    self.remaining_gas = is.read_uint64()?;
                },
                50 => {
                    self.output_data = is.read_bytes()?;
                },
                58 => {
                    self.sub_action_results.push(is.read_message()?);
                },
                66 => {
                    self.contract = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.input_action.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.success != false {
            my_size += 1 + 1;
        }
        if !self.error.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.error);
        }
        if self.gas_used != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.gas_used);
        }
        if self.remaining_gas != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.remaining_gas);
        }
        if !self.output_data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.output_data);
        }
        for value in &self.sub_action_results {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if !self.contract.is_empty() {
            my_size += ::protobuf::rt::bytes_size(8, &self.contract);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.input_action.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.success != false {
            os.write_bool(2, self.success)?;
        }
        if !self.error.is_empty() {
            os.write_string(3, &self.error)?;
        }
        if self.gas_used != 0 {
            os.write_uint64(4, self.gas_used)?;
        }
        if self.remaining_gas != 0 {
            os.write_uint64(5, self.remaining_gas)?;
        }
        if !self.output_data.is_empty() {
            os.write_bytes(6, &self.output_data)?;
        }
        for v in &self.sub_action_results {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        };
        if !self.contract.is_empty() {
            os.write_bytes(8, &self.contract)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ActionResult {
        ActionResult::new()
    }

    fn clear(&mut self) {
        self.input_action.clear();
        self.success = false;
        self.error.clear();
        self.gas_used = 0;
        self.remaining_gas = 0;
        self.output_data.clear();
        self.sub_action_results.clear();
        self.contract.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ActionResult {
        static instance: ActionResult = ActionResult {
            input_action: ::protobuf::MessageField::none(),
            success: false,
            error: ::std::string::String::new(),
            gas_used: 0,
            remaining_gas: 0,
            output_data: ::std::vec::Vec::new(),
            sub_action_results: ::std::vec::Vec::new(),
            contract: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ActionResult {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ActionResult").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ActionResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ActionResult {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:models.PromiseResult)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PromiseResult {
    // message fields
    // @@protoc_insertion_point(field:models.PromiseResult.success)
    pub success: bool,
    // @@protoc_insertion_point(field:models.PromiseResult.data)
    pub data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:models.PromiseResult.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PromiseResult {
    fn default() -> &'a PromiseResult {
        <PromiseResult as ::protobuf::Message>::default_instance()
    }
}

impl PromiseResult {
    pub fn new() -> PromiseResult {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "success",
            |m: &PromiseResult| { &m.success },
            |m: &mut PromiseResult| { &mut m.success },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &PromiseResult| { &m.data },
            |m: &mut PromiseResult| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PromiseResult>(
            "PromiseResult",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PromiseResult {
    const NAME: &'static str = "PromiseResult";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.success = is.read_bool()?;
                },
                18 => {
                    self.data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.success != false {
            my_size += 1 + 1;
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.success != false {
            os.write_bool(1, self.success)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(2, &self.data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PromiseResult {
        PromiseResult::new()
    }

    fn clear(&mut self) {
        self.success = false;
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PromiseResult {
        static instance: PromiseResult = PromiseResult {
            success: false,
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PromiseResult {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PromiseResult").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PromiseResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PromiseResult {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:models.InvocationContext)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct InvocationContext {
    // message fields
    // @@protoc_insertion_point(field:models.InvocationContext.is_callback)
    pub is_callback: bool,
    // @@protoc_insertion_point(field:models.InvocationContext.promise_result)
    pub promise_result: ::protobuf::MessageField<PromiseResult>,
    // special fields
    // @@protoc_insertion_point(special_field:models.InvocationContext.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a InvocationContext {
    fn default() -> &'a InvocationContext {
        <InvocationContext as ::protobuf::Message>::default_instance()
    }
}

impl InvocationContext {
    pub fn new() -> InvocationContext {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_callback",
            |m: &InvocationContext| { &m.is_callback },
            |m: &mut InvocationContext| { &mut m.is_callback },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, PromiseResult>(
            "promise_result",
            |m: &InvocationContext| { &m.promise_result },
            |m: &mut InvocationContext| { &mut m.promise_result },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<InvocationContext>(
            "InvocationContext",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for InvocationContext {
    const NAME: &'static str = "InvocationContext";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.is_callback = is.read_bool()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.promise_result)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.is_callback != false {
            my_size += 1 + 1;
        }
        if let Some(v) = self.promise_result.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.is_callback != false {
            os.write_bool(1, self.is_callback)?;
        }
        if let Some(v) = self.promise_result.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> InvocationContext {
        InvocationContext::new()
    }

    fn clear(&mut self) {
        self.is_callback = false;
        self.promise_result.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static InvocationContext {
        static instance: InvocationContext = InvocationContext {
            is_callback: false,
            promise_result: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for InvocationContext {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("InvocationContext").unwrap()).clone()
    }
}

impl ::std::fmt::Display for InvocationContext {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InvocationContext {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cmodels.proto\x12\x06models\"t\n\tProtoArgs\x12.\n\x04args\x18\x01\
    \x20\x03(\x0b2\x1a.models.ProtoArgs.ArgumentR\x04args\x1a7\n\x08Argument\
    \x12\x14\n\x05value\x18\x01\x20\x01(\x0cR\x05value\x12\x15\n\x06is_nil\
    \x18\x02\x20\x01(\x08R\x05isNil\"\xc6\x01\n\x06Action\x12\x1f\n\x0bactio\
    n_type\x18\x01\x20\x01(\rR\nactionType\x12\x16\n\x06amount\x18\x02\x20\
    \x01(\x0cR\x06amount\x12\x16\n\x06method\x18\x03\x20\x01(\tR\x06method\
    \x12\x12\n\x04args\x18\x04\x20\x01(\x0cR\x04args\x12\x1b\n\tgas_limit\
    \x18\x05\x20\x01(\x04R\x08gasLimit\x12\x12\n\x04code\x18\x06\x20\x01(\
    \x0cR\x04code\x12\x14\n\x05nonce\x18\x07\x20\x01(\x0cR\x05nonce\x12\x10\
    \n\x03key\x18\x08\x20\x01(\x0cR\x03key\"\xb2\x02\n\x0cActionResult\x121\
    \n\x0cinput_action\x18\x01\x20\x01(\x0b2\x0e.models.ActionR\x0binputActi\
    on\x12\x18\n\x07success\x18\x02\x20\x01(\x08R\x07success\x12\x14\n\x05er\
    ror\x18\x03\x20\x01(\tR\x05error\x12\x19\n\x08gas_used\x18\x04\x20\x01(\
    \x04R\x07gasUsed\x12#\n\rremaining_gas\x18\x05\x20\x01(\x04R\x0cremainin\
    gGas\x12\x1f\n\x0boutput_data\x18\x06\x20\x01(\x0cR\noutputData\x12B\n\
    \x12sub_action_results\x18\x07\x20\x03(\x0b2\x14.models.ActionResultR\
    \x10subActionResults\x12\x1a\n\x08contract\x18\x08\x20\x01(\x0cR\x08cont\
    ract\"=\n\rPromiseResult\x12\x18\n\x07success\x18\x01\x20\x01(\x08R\x07s\
    uccess\x12\x12\n\x04data\x18\x02\x20\x01(\x0cR\x04data\"r\n\x11Invocatio\
    nContext\x12\x1f\n\x0bis_callback\x18\x01\x20\x01(\x08R\nisCallback\x12<\
    \n\x0epromise_result\x18\x02\x20\x01(\x0b2\x15.models.PromiseResultR\rpr\
    omiseResultb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(ProtoArgs::generated_message_descriptor_data());
            messages.push(Action::generated_message_descriptor_data());
            messages.push(ActionResult::generated_message_descriptor_data());
            messages.push(PromiseResult::generated_message_descriptor_data());
            messages.push(InvocationContext::generated_message_descriptor_data());
            messages.push(proto_args::Argument::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
