name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

defaults:
  run:
    shell: bash
jobs:
  release:
    env:
      BINARY_NAME: libidena_wasm.a
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-latest
            artifact_name: 'libidena_wasm_linux_amd64.a'
            target: ''
          - build: macos-x64
            os: macos-latest
            artifact_name: 'libidena_wasm_darwin_amd64.a'
            target: ''
          - build: macos-arm64
            os: macos-latest
            artifact_name: 'libidena_wasm_darwin_arm64.a'
            target: aarch64-apple-darwin
          - build: windows-x64
            os: windows-latest
            artifact_name: 'libidena_wasm_windows_amd64.a'
            target: x86_64-pc-windows-gnu
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        if: matrix.target == ''

      - uses: dtolnay/rust-toolchain@stable
        if: matrix.target != ''
        with:
          targets: ${{ matrix.target }}

      - name: Install Windows GNU linker
        if: matrix.os == 'windows-latest'
        run: choco install -y mingw

      - name: Build
        run: |
          target="${{ matrix.target }}"
          if [[ -n "${target}" ]]; then
            cargo build --release --all-features --target "${target}"
          else
            cargo build --release --all-features
          fi

      - name: Rename output file
        run: |
          asset_name=${{ matrix.artifact_name }}
          if [[ -n "${{ matrix.target }}" ]]; then
            mv target/${{ matrix.target }}/release/${BINARY_NAME} ${asset_name}
          else
            mv target/release/${BINARY_NAME} ${asset_name}
          fi
          echo "ASSET_NAME=${asset_name}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.ASSET_NAME }}

  linux_aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: libidena_wasm.a
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Build cross image
        run: |
          docker build -t idena-wasm/aarch64 ${GITHUB_WORKSPACE}/.github/cross-linux-aarch64/
        env:
          CROSS_DOCKER_IN_DOCKER: true
      - name: Build idena-wasm binary
        run: |
          ${CARGO_BINARY} build --target=aarch64-unknown-linux-gnu --release
        env:
          CARGO_BINARY: docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/project -w /project idena-wasm/aarch64 cross
          CROSS_DOCKER_IN_DOCKER: true
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
          PKG_CONFIG_ALLOW_CROSS: true
      - name: Rename output file
        run: |
          asset_name=libidena_wasm_linux_aarch64.a
          cp target/aarch64-unknown-linux-gnu/release/${BINARY_NAME} ${asset_name}
          echo "ASSET_NAME=${asset_name}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.ASSET_NAME }}
