//! Builds the idena-wasm `ProtoArgs` decoder next to the rust-protobuf 2.27.1
//! code the network uses, so the two can be compared on the same input.

// Same sibling layout as `src/proto/` in idena-wasm, so `super::models`
// resolves in the included decoder.
#[path = "../../../src/proto/legacy_args.rs"]
pub mod legacy_args;
#[path = "../../../src/proto/models.rs"]
pub mod models;

// Generated by rust-protobuf 2.27.1 for an older compiler; kept verbatim.
#[rustfmt::skip]
#[allow(warnings, clippy::all)]
mod legacy_models_v2;

/// Decoded argument as `(value, is_nil)`.
pub type DecodedArg = (Vec<u8>, bool);

/// Decodes with the idena-wasm decoder.
pub fn decode_current(data: &[u8]) -> Option<Vec<DecodedArg>> {
    legacy_args::decode_proto_args(data)
        .ok()
        .map(|args| args.into_iter().map(|a| (a.value, a.is_nil)).collect())
}

/// Decodes with the rust-protobuf 2.27.1 generated code.
pub fn decode_legacy(data: &[u8]) -> Option<Vec<DecodedArg>> {
    use protobuf_legacy::Message;

    legacy_models_v2::ProtoArgs::parse_from_bytes(data)
        .ok()
        .map(|args| {
            args.get_args()
                .iter()
                .map(|a| (a.get_value().to_vec(), a.get_is_nil()))
                .collect()
        })
}

/// Decodes with the rust-protobuf 3 generated code (the parser this decoder
/// replaced), to demonstrate the divergence.
pub fn decode_protobuf3(data: &[u8]) -> Option<Vec<DecodedArg>> {
    use protobuf::Message;

    models::ProtoArgs::parse_from_bytes(data)
        .ok()
        .map(|args| args.args.into_iter().map(|a| (a.value, a.is_nil)).collect())
}
